### ISSUE TITLE
Create account for players

### ISSUE THREAD

**Issue by ofux** [onlydustxyz/starkonquest#43]
### Details

As a player, I want to have an account keeping data about me.

Players should be able to create an account on-chain that will store their:
- nickname
- won tournament count
- lost tournament count
- won battle count
- lost battle count

The account will probably contains more data in the future, so the solution should be extensible.
When a player registers a ship, the tournament contract checks he owns an account.

### Acceptance Criteria

- accounts must be managed by a specific contract (might be a NFT)
- the tournament checks player account when a ship is registered
- won/lost tournament/battle count is well updated every time a tournament runs
- there must be some documentation describing how to create an account
- it must be thoroughly tested

**Comment by ltoussaint** [comment]
@ofux is this account automatically created when registering to a tournament for the first time? Or does the FrontEnd need to do it by a user manual action?
