### ISSUE TITLE
Write a faster implementation of grid

### ISSUE THREAD

**Issue by ofux** [onlydustxyz/starkonquest#47]
### Details

As a tournament admin, I want a battle to be executed quickly and at low cost.

The current implementation of the grid is quite inefficient as it uses an array containing all the cells of the grid. When a single cell changes, the whole array must be copied into a new one as Cairo's memory is read-only.

A better approach would be to use [dictionaries](https://www.cairo-lang.org/docs/reference/common_library.html#common-library-dict) to implement a new version of `square_grid.cairo`.

### Acceptance Criteria

- the new grid must implement the same interface than `square_grid.cairo`
- all tests passing on the current grid implementation must pass on the new one
- the new implementation must be faster and cost less steps (prove it)
- no storage must be used

**Comment by omnisat** [comment]
working on it ...
